// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Artist(arg1:string):Promise<any>;

export function Genres(arg1:string):Promise<any>;
