// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Artist(arg1) {
  return window['go']['main']['App']['Artist'](arg1);
}

export function Genres(arg1) {
  return window['go']['main']['App']['Genres'](arg1);
}
